---
  - name: "Install packages for all"
    hosts: all

    tasks:
      - apt:
          name:
            - gcc
            - g++
            - jq
            - make
            - tree

      - snap:
          name: code
          classic: yes