---
  - name: "Install packages for all"
    hosts: all

    tasks:
      - apt:
          name:
            - gcc
            - g++
            - jq
            - make
            - tree

      - snap:
          name: code
          classic: yes

  - name: "Install packages for personal_work"
    hosts: personal_work

    tasks:
      - apt:
          name:
            - bat
            - copyq
            - exa
            - terminator

    tasks:
      - snap:
          name:
            - pinta
            - spotify
            - vlc
    
    tasks:
      - pip:
          name:
            - tldr
  
    tasks:
      - name: "Install mcfly"
        shell: curl -LSfs https://raw.githubusercontent.com/cantino/mcfly/master/ci/install.sh | sh -s -- --git cantino/mcfly
        args:
          creates: /usr/local/bin/mcfly

