---
  - name: "Install packages for all"
    hosts: all

    tasks:
      - apt:
          - gcc
          - g++
          - jq
          - make
          - tree

      - snap:
          name: code
          classic: yes