---
  - name: "Install packages for all"
    hosts: all

    tasks:
      - apt:
          name:
            - gcc
            - g++
            - jq
            - make
            - tree

      - snap:
          name: code
          classic: yes

  - name: "Install packages for personal_work"
    hosts: personal_work

    tasks:
      - apt:
          name:
            - bat
            - copyq
            - exa
            - terminator

      - snap:
          name:
            - pinta
            - spotify
            - vlc

      - pip:
          name:
            - tldr
  
      - name: "Install mcfly"
        shell: curl -LSfs https://raw.githubusercontent.com/cantino/mcfly/master/ci/install.sh | sh -s -- --git cantino/mcfly
        args:
          creates: /usr/local/bin/mcfly
      
      - name: "Download lyncser"
        script: download_latest_github_release.py chrismcgehee lyncser
        args:
          creates: /usr/local/bin/lyncser
      - name: "Install lyncser"
        shell: lyncser_*/install/install.sh
        args:
          creates: /usr/local/bin/lyncser
      

      - name: "Install go"
        shell: 
          wget "https://dl.google.com/go/$(wget -O - https://golang.org/VERSION?m=text).linux-amd64.tar.gz"
          tar -C /usr/local -xzf ./*.linux-amd64.tar.gz
          mkdir $HOME/.go
          ln -s $HOME/.go $HOME/go
        args:
          creates: /usr/local/go/bin
      
      - name: "Install curlie"
        shell: go install github.com/rs/curlie@latest && ln -s $HOME/.go/bin/curlie /usr/local/bin/curlie
        args:
          creates: /usr/local/bin/curlie

